module Compiler.Generate.Rust exposing
    ( Mains
    , generate
    )

import Compiler.AST.Optimized as Opt
import Compiler.Data.Index as Index
import Compiler.Data.Name as Name
import Compiler.Generate.Mode as Mode
import Compiler.Generate.Rust.Builder as RB
import Compiler.Generate.Target exposing (Target)
import Compiler.Guida.ModuleName as ModuleName
import Compiler.Optimize.DecisionTree as DT
import Compiler.Reporting.Annotation as A
import Data.Map as Dict exposing (Dict)
import Data.Set as EverySet exposing (EverySet)
import System.TypeCheck.IO as IO
import Utils.Main as Utils



-- GENERATE


type alias Mains =
    Dict (List String) IO.Canonical Opt.Main


type alias Graph =
    Dict (List String) Opt.Global Opt.Node


type State
    = State (List RB.Stmt) (EverySet (List String) Opt.Global)


emptyState : State
emptyState =
    State [] EverySet.empty


generate : Target -> Mode.Mode -> Opt.GlobalGraph -> Mains -> String
generate _ mode (Opt.GlobalGraph graph _) mains =
    let
        state : State
        state =
            Dict.foldr ModuleName.compareCanonical (addMain mode graph) emptyState mains

        modules : List String
        modules =
            Dict.foldr ModuleName.compareCanonical gatherModules [] mains

        moduleEntries : String
        moduleEntries =
            String.concat (List.map toModuleEntry modules)

        initFunctions : String
        initFunctions =
            String.concat (List.map toInitFunction modules)

        valuesBody : String
        valuesBody =
            stateToString state
    in
    "// Generated by Guida (Rust backend preview).\n"
        ++ "// This is the first implementation slice and does not yet contain full Guida semantics.\n\n"
        ++ "pub fn generated_modules() -> &'static [&'static str] {\n"
        ++ "    &[\n"
        ++ moduleEntries
        ++ "    ]\n"
        ++ "}\n\n"
        ++ "pub fn generated_values() {\n"
        ++ valuesBody
        ++ "}\n\n"
        ++ initFunctions


addMain : Mode.Mode -> Graph -> IO.Canonical -> Opt.Main -> State -> State
addMain mode graph home _ state =
    addGlobal mode graph state (Opt.Global home "main")


addGlobal : Mode.Mode -> Graph -> State -> Opt.Global -> State
addGlobal mode graph ((State stmts seen) as state) global =
    if EverySet.member Opt.toComparableGlobal global seen then
        state

    else
        addGlobalHelp mode graph global <|
            State stmts (EverySet.insert Opt.toComparableGlobal global seen)


addGlobalHelp : Mode.Mode -> Graph -> Opt.Global -> State -> State
addGlobalHelp mode graph global state =
    let
        addDeps : EverySet (List String) Opt.Global -> State -> State
        addDeps deps someState =
            let
                sortedDeps : List Opt.Global
                sortedDeps =
                    List.sortWith Opt.compareGlobal (EverySet.toList Opt.compareGlobal deps)
            in
            List.foldl (\dep acc -> addGlobal mode graph acc dep) someState sortedDeps

        globalName : String
        globalName =
            toGlobalIdentifier global
    in
    case Utils.find Opt.toComparableGlobal global graph of
        Opt.Define expr deps ->
            addStmt (addDeps deps state) (RB.Let globalName (toExpr expr))

        Opt.TrackedDefine _ expr deps ->
            addStmt (addDeps deps state) (RB.Let globalName (toExpr expr))

        Opt.Ctor index arity ->
            addStmt state
                (RB.Let globalName
                    (RB.ExprCall
                        (RB.ExprRef "guida_ctor")
                        [ RB.ExprInt (indexToInt index)
                        , RB.ExprInt arity
                        ]
                    )
                )

        Opt.Enum index ->
            addStmt state (RB.Let globalName (RB.ExprInt (indexToInt index)))

        Opt.Link linkedGlobal ->
            addGlobal mode graph state linkedGlobal

        Opt.DefineTailFunc _ argNames body deps ->
            addStmt (addDeps deps state) (RB.Let globalName (toClosureExpr argNames body))

        Opt.Cycle names values functions defs ->
            addStmts (addDeps defs state) (generateCycleStmts global globalName names values functions)

        Opt.Manager effectsType ->
            addStmt state
                (RB.Let globalName
                    (RB.ExprCall
                        (RB.ExprRef "guida_manager")
                        [ RB.ExprString (effectsTypeToString effectsType) ]
                    )
                )

        Opt.Kernel chunks deps ->
            addStmt (addDeps deps state)
                (RB.Let globalName
                    (RB.ExprCall
                        (RB.ExprRef "guida_kernel")
                        [ RB.ExprInt (List.length chunks)
                        , RB.ExprBool (isDebugMode mode)
                        ]
                    )
                )

        Opt.Box ->
            addStmt state
                (RB.Let globalName
                    (RB.ExprCall (RB.ExprRef "guida_box") [ RB.ExprString globalName ])
                )

        Opt.PortIncoming decoder deps ->
            addStmt (addDeps deps state)
                (RB.Let globalName
                    (RB.ExprCall
                        (RB.ExprRef "guida_incoming_port")
                        [ RB.ExprString globalName
                        , toExpr decoder
                        ]
                    )
                )

        Opt.PortOutgoing encoder deps ->
            addStmt (addDeps deps state)
                (RB.Let globalName
                    (RB.ExprCall
                        (RB.ExprRef "guida_outgoing_port")
                        [ RB.ExprString globalName
                        , toExpr encoder
                        ]
                    )
                )


isDebugMode : Mode.Mode -> Bool
isDebugMode mode =
    case mode of
        Mode.Dev _ ->
            True

        Mode.Prod _ ->
            False


addStmt : State -> RB.Stmt -> State
addStmt (State stmts seen) stmt =
    State (stmt :: stmts) seen


addStmts : State -> List RB.Stmt -> State
addStmts state stmts =
    List.foldl (\stmt acc -> addStmt acc stmt) state stmts


stateToString : State -> String
stateToString (State revStmts _) =
    List.foldl RB.stmtToBuilder RB.emptyBuilder (List.reverse revStmts)
        |> RB.toString


toGlobalIdentifier : Opt.Global -> String
toGlobalIdentifier (Opt.Global (IO.Canonical _ moduleName) name) =
    toRustIdentifier (moduleName ++ "." ++ name)


indexToInt : Index.ZeroBased -> Int
indexToInt index =
    Index.toMachine index


toExpr : Opt.Expr -> RB.Expr
toExpr expr =
    case expr of
        Opt.Bool _ value ->
            RB.ExprBool value

        Opt.Str _ value ->
            RB.ExprString value

        Opt.Chr _ value ->
            RB.ExprString value

        Opt.Int _ value ->
            RB.ExprInt value

        Opt.Float _ value ->
            let
                asString : String
                asString =
                    if value == toFloat (floor value) then
                        String.fromFloat value ++ ".0"

                    else
                        String.fromFloat value
            in
            RB.ExprFloat asString

        Opt.VarLocal name ->
            RB.ExprRef (toRustIdentifier name)

        Opt.TrackedVarLocal _ name ->
            RB.ExprRef (toRustIdentifier name)

        Opt.VarGlobal _ global ->
            RB.ExprRef (toGlobalIdentifier global)

        Opt.VarKernel _ home localName ->
            RB.ExprRef (toRustIdentifier ("kernel." ++ home ++ "." ++ localName))

        Opt.VarEnum _ global _ ->
            RB.ExprRef (toGlobalIdentifier global)

        Opt.VarBox _ global ->
            RB.ExprRef (toGlobalIdentifier global)

        Opt.VarCycle _ home localName ->
            RB.ExprRef (toCycleIdentifier home localName)

        Opt.VarDebug _ name _ _ ->
            RB.ExprRef (toRustIdentifier ("debug." ++ name))

        Opt.Call _ fn args ->
            RB.ExprCall (toExpr fn) (List.map toExpr args)

        Opt.If branches finalExpr ->
            branchesToExpr branches (toExpr finalExpr)

        Opt.Record fields ->
            RB.ExprCall (RB.ExprRef "guida_record") (recordFieldsToArgs fields)

        Opt.TrackedRecord _ fields ->
            RB.ExprCall (RB.ExprRef "guida_record") (trackedRecordFieldsToArgs fields)

        Opt.Access value _ field ->
            RB.ExprCall
                (RB.ExprRef "guida_get")
                [ toExpr value
                , RB.ExprString field
                ]

        Opt.Accessor _ field ->
            RB.ExprCall
                (RB.ExprRef "guida_accessor")
                [ RB.ExprString field ]

        Opt.Unit ->
            RB.ExprRef "()"

        Opt.Tuple _ a b cs ->
            RB.ExprCall (RB.ExprRef "guida_tuple") (List.map toExpr (a :: b :: cs))

        Opt.List _ entries ->
            RB.ExprCall (RB.ExprRef "guida_list") (List.map toExpr entries)

        Opt.Update _ record fields ->
            RB.ExprCall
                (RB.ExprRef "guida_update")
                [ toExpr record
                , RB.ExprCall (RB.ExprRef "guida_record") (locatedRecordUpdatesToArgs fields)
                ]

        Opt.Function args body ->
            RB.ExprClosure (List.map toRustIdentifier args) (toExpr body)

        Opt.TrackedFunction args body ->
            RB.ExprClosure (List.map (toRustIdentifier << locatedNameToName) args) (toExpr body)

        Opt.TailCall name args ->
            RB.ExprCall
                (RB.ExprRef (toRustIdentifier name))
                (List.map (toExpr << Tuple.second) args)

        Opt.Let def body ->
            toLetExpr def body

        Opt.Destruct (Opt.Destructor name path) body ->
            RB.ExprCall
                (RB.ExprRef "guida_destruct")
                [ RB.ExprString name
                , pathToExpr path
                , toExpr body
                ]

        Opt.Case label root decider jumps ->
            RB.ExprCall
                (RB.ExprRef "guida_case")
                [ RB.ExprString label
                , RB.ExprRef (toRustIdentifier root)
                , deciderToExpr decider
                , jumpsToExpr jumps
                ]

        Opt.Shader _ attributes uniforms ->
            RB.ExprCall
                (RB.ExprRef "guida_shader")
                [ RB.ExprInt (EverySet.size attributes)
                , RB.ExprInt (EverySet.size uniforms)
                ]


toClosureExpr : List (A.Located Name.Name) -> Opt.Expr -> RB.Expr
toClosureExpr args body =
    RB.ExprClosure
        (List.map (toRustIdentifier << locatedNameToName) args)
        (toExpr body)


toLetExpr : Opt.Def -> Opt.Expr -> RB.Expr
toLetExpr def bodyExpr =
    case def of
        Opt.Def _ name valueExpr ->
            RB.ExprCall
                (RB.ExprRef "guida_let")
                [ RB.ExprString name
                , toExpr valueExpr
                , toExpr bodyExpr
                ]

        Opt.TailDef _ name args valueExpr ->
            RB.ExprCall
                (RB.ExprRef "guida_let")
                [ RB.ExprString name
                , RB.ExprClosure (List.map (toRustIdentifier << locatedNameToName) args) (toExpr valueExpr)
                , toExpr bodyExpr
                ]


generateCycleStmts : Opt.Global -> String -> List Name.Name -> List ( Name.Name, Opt.Expr ) -> List Opt.Def -> List RB.Stmt
generateCycleStmts global globalName names values functions =
    let
        cycleLabel : String
        cycleLabel =
            "cycle group: " ++ String.join ", " names
    in
    RB.Comment cycleLabel
        :: (List.map generateCycleValue values
                ++ List.map generateCycleFunction functions
                ++ [ RB.Let globalName (RB.ExprRef (toCycleRootIdentifier global)) ]
           )


generateCycleValue : ( Name.Name, Opt.Expr ) -> RB.Stmt
generateCycleValue ( name, expr ) =
    RB.Let (toRustIdentifier ("cycle.value." ++ name)) (toExpr expr)


generateCycleFunction : Opt.Def -> RB.Stmt
generateCycleFunction def =
    case def of
        Opt.Def _ name expr ->
            RB.Let (toRustIdentifier ("cycle.fn." ++ name)) (toExpr expr)

        Opt.TailDef _ name args expr ->
            RB.Let
                (toRustIdentifier ("cycle.fn." ++ name))
                (RB.ExprClosure (List.map locatedNameToName args) (toExpr expr))


toCycleRootIdentifier : Opt.Global -> String
toCycleRootIdentifier (Opt.Global (IO.Canonical _ moduleName) _) =
    toRustIdentifier ("cycle.root." ++ moduleName)


locatedNameToName : A.Located Name.Name -> Name.Name
locatedNameToName (A.At _ name) =
    name


branchesToExpr : List ( Opt.Expr, Opt.Expr ) -> RB.Expr -> RB.Expr
branchesToExpr branches fallbackExpr =
    case branches of
        [] ->
            fallbackExpr

        ( condition, branchExpr ) :: rest ->
            RB.ExprIf (toExpr condition) (toExpr branchExpr) (branchesToExpr rest fallbackExpr)


recordFieldsToArgs : Dict String Name.Name Opt.Expr -> List RB.Expr
recordFieldsToArgs fields =
    Dict.toList compare fields
        |> List.concatMap
            (\( field, value ) ->
                [ RB.ExprString field
                , toExpr value
                ]
            )


trackedRecordFieldsToArgs : Dict String (A.Located Name.Name) Opt.Expr -> List RB.Expr
trackedRecordFieldsToArgs fields =
    Dict.toList compareLocatedName fields
        |> List.concatMap
            (\( A.At _ fieldName, valueExpr ) ->
                [ RB.ExprString fieldName
                , toExpr valueExpr
                ]
            )


locatedRecordUpdatesToArgs : Dict String (A.Located Name.Name) Opt.Expr -> List RB.Expr
locatedRecordUpdatesToArgs fields =
    Dict.toList compareLocatedName fields
        |> List.concatMap
            (\( A.At _ fieldName, valueExpr ) ->
                [ RB.ExprString fieldName
                , toExpr valueExpr
                ]
            )


compareLocatedName : A.Located Name.Name -> A.Located Name.Name -> Order
compareLocatedName (A.At _ name1) (A.At _ name2) =
    compare name1 name2


toCycleIdentifier : IO.Canonical -> Name.Name -> String
toCycleIdentifier (IO.Canonical _ moduleName) localName =
    toRustIdentifier ("cycle." ++ moduleName ++ "." ++ localName)


effectsTypeToString : Opt.EffectsType -> String
effectsTypeToString effectsType =
    case effectsType of
        Opt.Cmd ->
            "cmd"

        Opt.Sub ->
            "sub"

        Opt.Fx ->
            "fx"


pathToExpr : Opt.Path -> RB.Expr
pathToExpr path =
    case path of
        Opt.Index index childPath ->
            RB.ExprCall
                (RB.ExprRef "guida_path_index")
                [ RB.ExprInt (indexToInt index)
                , pathToExpr childPath
                ]

        Opt.ArrayIndex index childPath ->
            RB.ExprCall
                (RB.ExprRef "guida_path_array_index")
                [ RB.ExprInt index
                , pathToExpr childPath
                ]

        Opt.Field field childPath ->
            RB.ExprCall
                (RB.ExprRef "guida_path_field")
                [ RB.ExprString field
                , pathToExpr childPath
                ]

        Opt.Unbox childPath ->
            RB.ExprCall
                (RB.ExprRef "guida_path_unbox")
                [ pathToExpr childPath ]

        Opt.Root rootName ->
            RB.ExprCall
                (RB.ExprRef "guida_path_root")
                [ RB.ExprString rootName ]


deciderToExpr : Opt.Decider Opt.Choice -> RB.Expr
deciderToExpr decider =
    case decider of
        Opt.Leaf choice ->
            choiceToExpr choice

        Opt.Chain tests success failure ->
            RB.ExprCall
                (RB.ExprRef "guida_decider_chain")
                [ chainTestsToExpr tests
                , deciderToExpr success
                , deciderToExpr failure
                ]

        Opt.FanOut path edges fallback ->
            RB.ExprCall
                (RB.ExprRef "guida_decider_fanout")
                [ dtPathToExpr path
                , fanOutEdgesToExpr edges
                , deciderToExpr fallback
                ]


choiceToExpr : Opt.Choice -> RB.Expr
choiceToExpr choice =
    case choice of
        Opt.Inline expr ->
            RB.ExprCall
                (RB.ExprRef "guida_choice_inline")
                [ toExpr expr ]

        Opt.Jump index ->
            RB.ExprCall
                (RB.ExprRef "guida_choice_jump")
                [ RB.ExprInt index ]


chainTestsToExpr : List ( DT.Path, DT.Test ) -> RB.Expr
chainTestsToExpr tests =
    RB.ExprCall
        (RB.ExprRef "guida_list")
        (List.map chainTestToExpr tests)


chainTestToExpr : ( DT.Path, DT.Test ) -> RB.Expr
chainTestToExpr ( path, test ) =
    RB.ExprCall
        (RB.ExprRef "guida_chain_test")
        [ dtPathToExpr path
        , dtTestToExpr test
        ]


fanOutEdgesToExpr : List ( DT.Test, Opt.Decider Opt.Choice ) -> RB.Expr
fanOutEdgesToExpr edges =
    RB.ExprCall
        (RB.ExprRef "guida_list")
        (List.map fanOutEdgeToExpr edges)


fanOutEdgeToExpr : ( DT.Test, Opt.Decider Opt.Choice ) -> RB.Expr
fanOutEdgeToExpr ( test, decider ) =
    RB.ExprCall
        (RB.ExprRef "guida_fanout_edge")
        [ dtTestToExpr test
        , deciderToExpr decider
        ]


jumpsToExpr : List ( Int, Opt.Expr ) -> RB.Expr
jumpsToExpr jumps =
    RB.ExprCall
        (RB.ExprRef "guida_list")
        (List.map jumpToExpr jumps)


jumpToExpr : ( Int, Opt.Expr ) -> RB.Expr
jumpToExpr ( index, expr ) =
    RB.ExprCall
        (RB.ExprRef "guida_jump")
        [ RB.ExprInt index
        , toExpr expr
        ]


dtPathToExpr : DT.Path -> RB.Expr
dtPathToExpr path =
    case path of
        DT.Index index childPath ->
            RB.ExprCall
                (RB.ExprRef "guida_dt_path_index")
                [ RB.ExprInt (indexToInt index)
                , dtPathToExpr childPath
                ]

        DT.Unbox childPath ->
            RB.ExprCall
                (RB.ExprRef "guida_dt_path_unbox")
                [ dtPathToExpr childPath ]

        DT.Empty ->
            RB.ExprCall (RB.ExprRef "guida_dt_path_empty") []


dtTestToExpr : DT.Test -> RB.Expr
dtTestToExpr test =
    case test of
        DT.IsCtor (IO.Canonical _ moduleName) name index numAlts _ ->
            RB.ExprCall
                (RB.ExprRef "guida_dt_test_ctor")
                [ RB.ExprString moduleName
                , RB.ExprString name
                , RB.ExprInt (indexToInt index)
                , RB.ExprInt numAlts
                ]

        DT.IsCons ->
            RB.ExprCall (RB.ExprRef "guida_dt_test_cons") []

        DT.IsNil ->
            RB.ExprCall (RB.ExprRef "guida_dt_test_nil") []

        DT.IsTuple ->
            RB.ExprCall (RB.ExprRef "guida_dt_test_tuple") []

        DT.IsInt value ->
            RB.ExprCall (RB.ExprRef "guida_dt_test_int") [ RB.ExprInt value ]

        DT.IsChr value ->
            RB.ExprCall (RB.ExprRef "guida_dt_test_chr") [ RB.ExprString value ]

        DT.IsStr value ->
            RB.ExprCall (RB.ExprRef "guida_dt_test_str") [ RB.ExprString value ]

        DT.IsBool value ->
            RB.ExprCall (RB.ExprRef "guida_dt_test_bool") [ RB.ExprBool value ]


gatherModules : IO.Canonical -> Opt.Main -> List String -> List String
gatherModules (IO.Canonical _ moduleName) _ names =
    moduleName :: names


toModuleEntry : String -> String
toModuleEntry moduleName =
    "        \""
        ++ moduleName
        ++ "\",\n"


toInitFunction : String -> String
toInitFunction moduleName =
    let
        body : String
        body =
            RB.emptyBuilder
                |> RB.stmtToBuilder (RB.Let "module_name" (RB.ExprString moduleName))
                |> RB.stmtToBuilder (RB.Return (RB.ExprRef "module_name"))
                |> RB.toString
    in
    "pub fn init_"
        ++ toRustIdentifier moduleName
        ++ "() -> &'static str {\n"
        ++ body
        ++ "}\n"


toRustIdentifier : String -> String
toRustIdentifier moduleName =
    "module_"
        ++ String.join "_" (Name.splitDots moduleName)
