module Compiler.Generate.Rust exposing
    ( Mains
    , generate
    )

import Compiler.AST.Optimized as Opt
import Compiler.Data.Name as Name
import Compiler.Generate.Mode as Mode
import Compiler.Generate.Target exposing (Target)
import Compiler.Guida.ModuleName as ModuleName
import Data.Map as Dict exposing (Dict)
import System.TypeCheck.IO as IO



-- GENERATE


type alias Mains =
    Dict (List String) IO.Canonical Opt.Main


generate : Target -> Mode.Mode -> Opt.GlobalGraph -> Mains -> String
generate _ _ _ mains =
    let
        modules : List String
        modules =
            Dict.foldr ModuleName.compareCanonical gatherModules [] mains

        moduleEntries : String
        moduleEntries =
            String.concat (List.map toModuleEntry modules)

        initFunctions : String
        initFunctions =
            String.concat (List.map toInitFunction modules)
    in
    "// Generated by Guida (Rust backend preview).\n"
        ++ "// This is the first implementation slice and does not yet contain full Guida semantics.\n\n"
        ++ "pub fn generated_modules() -> &'static [&'static str] {\n"
        ++ "    &[\n"
        ++ moduleEntries
        ++ "    ]\n"
        ++ "}\n\n"
        ++ initFunctions


gatherModules : IO.Canonical -> Opt.Main -> List String -> List String
gatherModules (IO.Canonical _ moduleName) _ names =
    moduleName :: names


toModuleEntry : String -> String
toModuleEntry moduleName =
    "        \""
        ++ moduleName
        ++ "\",\n"


toInitFunction : String -> String
toInitFunction moduleName =
    "pub fn init_"
        ++ toRustIdentifier moduleName
        ++ "() {}\n"


toRustIdentifier : String -> String
toRustIdentifier moduleName =
    "module_"
        ++ String.join "_" (Name.splitDots moduleName)
